# Generated by Django 5.1.2 on 2024-11-12 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome do novo Campus', max_length=250, verbose_name='Insira o nome do Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Insira a forma de ingresso')),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira a nova situação disponivel para o aluno', max_length=250, verbose_name='Insira a nova situção')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Insira o nome do curso')),
                ('campus', models.ForeignKey(help_text='Escolha o campus em que o curso é ofertado', on_delete=django.db.models.deletion.CASCADE, to='academico.campi')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Insira o nome completo do aluno', max_length=200, verbose_name='Nome')),
                ('cpf', models.CharField(help_text='Insira apenas os números sem caracteres especiais', max_length=11, unique=True, verbose_name='CPF')),
                ('matricula', models.CharField(editable=False, max_length=9, unique=True, verbose_name='Matricula')),
                ('dataNascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('foto', models.ImageField(upload_to='', verbose_name='Insira uma foto do aluno')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.campi', verbose_name='Campus')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.curso', verbose_name='Curso')),
                ('formaIngresso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.ingresso', verbose_name='Forma de ingresso')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.situacao', verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
