# Generated by Django 5.1.2 on 2024-11-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('aluno_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('matricula', models.IntegerField()),
                ('curso', models.CharField(max_length=100)),
                ('data_de_nascimento', models.DateField()),
            ],
        ),
    ]
