# Generated by Django 5.1.2 on 2024-11-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
